### ISSUE TITLE
Pokopom v2.1-21 Crash Epsxe Specific When Esc > Continue is Done

### ISSUE THREAD

**Issue by shinra358** [KrossX/Pokopom#10]
Esc continue works fine in pcsx2. Rumble stops when escape is pressed like it should.

However, in epsxe, rumble continues when esc is pressed and doesn't stop. Then when you press continue, the emu crashes.

In previous version Pokopom v2.1-17, it rumbled a little when esc was pressed but eventually it stopped. It did not crash when continue was pressed.

Expected behavior would be to have the controller not rumble during a rumble phase when escape is pressed and resume interrupted rumble when game is continued with no crash.

Tested on FFIX epsxe and FFXII pcsx2.

**Comment by KrossX** [comment]
I think the crash should be fixed with latest version. As for the rumble with esc/resume, I tested with older Pokopom versions and happens anyway. It appears to be a problem with ePSXe and its way of supporting plugins.

**Comment by shinra358** [comment]
Cool, I can confirm. Yeah, it's back to normal now. It stops after 2 secs when esc is pressed. Good enough for me!
