### ISSUE TITLE
PCSX2 Issue

### ISSUE THREAD

**Issue by shinra358** [KrossX/Pokopom#14]
It never ends, tsk tsk tsk.
Okay, with my controller off on pcsx2, the games boot fine. With my controller on, the game boots fine once, and then when I exit the emu and restart the emu, pcsx2 crashes. And crashes every tme afterwards. But when I switch to lilypad, everything works fine. So I switch back to pokopom and again, it only works the first time. Then after I restart pcsx2 it keeps crashing every time afterwards. Perhaps make an ini only option permanently for debug error logs so we can diagnose quicker if a future problem arises? Don't recall this happening at the time of our last talk back when you updated the plugin again. Maybe a new windows update is conflicting with something? _shrugs_. But it probably has something to do with the last update.

When I switched back to pokopom r127 to see if it happened, I got this error message when pcsx2 crashed on start:
<a href='https://postimg.org/image/v14xa6rgd/' target='_blank'><img src='https://s6.postimg.org/v14xa6rgd/poko.jpg' border='0' alt='postimage'/></a>

Could it be any of the following:
-memory leak
-runtime update needed 
?

And here is an error log when it crashes normally with the updated pokopom used:
[code]
Faulting application name: pcsx2.exe, version: 0.0.0.0, time stamp: 0x57c7df1c
Faulting module name: GSdx32-AVX.dll, version: 1.0.1.9, time stamp: 0x57c7df75
Exception code: 0xc0000005
Fault offset: 0x00039dd3
Faulting process id: 0x2978
Faulting application start time: 0x01d204ba486f3839
Faulting application path: E:\Users***\My Documents\Games\CONSOLE\EMULATORS\SONY\Playstation 2\pcsx2.exe
Faulting module path: E:\Users\***\My Documents\Games\CONSOLE\EMULATORS\SONY\Playstation 2\plugins\GSdx32-AVX.dll
Report Id: 89a79edd-70ad-11e6-9c89-8056f2ad9956

Fault bucket 1001185176, type 25
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: pcsx2.exe
P2: 0.0.0.0
P3: 57c7df1c
P4: GSdx32-AVX.dll
P5: 1.0.1.9
P6: 57c7df75
P7: c0000005
P8: 00039dd3
P9: 
P10: 

Attached files:
C:\Users\T Dean Jr\AppData\Local\Temp\WERF90B.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users***\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_pcsx2.exe_5f528f8cf25bec60a6fbaead876ee3b196eda2a7_2af400c9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 89a79edd-70ad-11e6-9c89-8056f2ad9956
Report Status: 1

Faulting application name: pcsx2.exe, version: 0.0.0.0, time stamp: 0x57c7df1c
Faulting module name: nvwgf2um.dll, version: 10.18.13.6869, time stamp: 0x577402cd
Exception code: 0xc0000005
Fault offset: 0x00743536
Faulting process id: 0x23d8
Faulting application start time: 0x01d204b9c6c41d3b
Faulting application path: E:\Users***\My Documents\Games\CONSOLE\EMULATORS\SONY\Playstation 2\pcsx2.exe
Faulting module path: C:\Windows\system32\nvwgf2um.dll
Report Id: 083aed59-70ad-11e6-9c89-8056f2ad9956

Fault bucket 1002161578, type 25
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: pcsx2.exe
P2: 0.0.0.0
P3: 57c7df1c
P4: nvwgf2um.dll
P5: 10.18.13.6869
P6: 577402cd
P7: c0000005
P8: 00743536
P9: 
P10: 

Attached files:
C:\Users***\AppData\Local\Temp\WERA8CA.tmp.WERInternalMetadata.xml
C:\Users\****\AppData\Local\Temp\WERAF9E.tmp.appcompat.txt

These files may be available here:
C:\Users***\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_pcsx2.exe_b6b9e433741ee2ac1da3f36ffa2ac18204fb327_2f3cb01a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 083aed59-70ad-11e6-9c89-8056f2ad9956

Faulting application name: pcsx2.exe, version: 0.0.0.0, time stamp: 0x57c7df1c
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x1560
Faulting application start time: 0x01d204b9b14098d7
Faulting application path: E:\Users***My Documents\Games\CONSOLE\EMULATORS\SONY\Playstation 2\pcsx2.exe
Faulting module path: unknown
Report Id: f372f384-70ac-11e6-9c89-8056f2ad9956

Fault bucket 50, type 5
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: pcsx2.exe
P2: 0.0.0.0
P3: 57c7df1c
P4: StackHash_0a9e
P5: 0.0.0.0
P6: 00000000
P7: 00000000
P8: c0000005
P9: 00000008
P10: 

Attached files:
C:\Users***\AppData\Local\Temp\WER2098.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users***\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_pcsx2.exe_66a8baf2ef2674f76abe785db6bdaf2d15a4312a_2de88237

Analysis symbol: 
Rechecking for solution: 0
Report Id: f372f384-70ac-11e6-9c89-8056f2ad9956
Report Status: 0[/code]

Edit: updating the nvidia drivers didn't seem to help.

**Comment by KrossX** [comment]
Well, that error log basically says "This is pcsx2's and gsdx's fault" mwahahaha! I don't remember ever getting into such issue, what controller and driver are you using?

**Comment by shinra358** [comment]
I'm using my ps4 controller with the scp server + ds4windows j2k
I thought it could be that or the nvidia drivers but it only happens with pokopom and not lilypad. So I don't get it lol.

368.69-notebook-win8-win7-64bit-international-whql
372.70-notebook-win8-win7-64bit-international-whql

These are the 2 graphics drivers I tried. Reverting back to before the gtx 980 for notebooks (sept 22, 2015) came out to see if it makes a difference.

**Comment by KrossX** [comment]
Hmmm... are you using a scp's xinput wrapper too?

**Comment by shinra358** [comment]
no, the server thingamabob that comes with ds4windows j2k

**Comment by KrossX** [comment]
I could not reproduce it. I tried opening a game and closing the emulator, repeat a few times. I did that with Pokopom r127 and my local latest (is rather old), with an X360 controller and a DS3 controller with scp driver.

**Comment by shinra358** [comment]
reverting to an older nvidia driver didn't help :(

doesn't happen in any emu I use pokopom in except pcsx2. doing a sfc scannow thing is see if there is any corruption anywhere. What are the newest runtimes that pokopom uses?

**Comment by KrossX** [comment]
Runtimes? I think latest official builds are VS2015. You should already have them though.

**Comment by shinra358** [comment]
k, every scan panned out ok. well i guess i can say that it isn't pokopom because I got it to do it on lily pad too. The game I kept testing it on was art of fighting anthology. But when I tested FF12, it didn't happen. So must be some kind of bug with the emu handling that game. I guess I can close this and go ask around in pcsx2 forums.
