### ISSUE TITLE
Sorry if this is the wrong place to ask. How do I toggle from analog mode to digital mode in ePSXe? 

### ISSUE THREAD

**Issue by Lion4K** [KrossX/Pokopom#23]
I'm using ePSXe 1.9.0 as this is the latest version Shark Enhanced supports, as the newer 2.x does not run on my PC for some reason unknown.

But while i'm on the BIOS or some older game, I need to open shark pad config and change to digital manually, I was wondering if theres a way to press a key like on the internal ePSXe pad plugin to swap modes.

Thanks for this awesome plugin, and sorry again if this is a bad place to ask.

**Comment by KrossX** [comment]
No problem, you can use either the controller's guide button or the keys 1 to 4. [WIKI](https://github.com/KrossX/Pokopom/wiki/Control-Scheme)

**Comment by Lion4K** [comment]
thank you very much!!!
