### ISSUE TITLE
No access to .dll

### ISSUE THREAD

**Issue by owoMermaid** [KrossX/Pokopom#28]
I read other Issue Posts and a forum that says the .dll is contained in the readme, BUT your google drive isn't accessable anymore, and I would really like to use your plugin. I've heard high things of it and would like to see for myself.

![image](https://user-images.githubusercontent.com/48803539/151663553-0ab3ef40-7a56-48d8-8bad-6f3db75e9d3c.png)

**Comment by owoMermaid** [comment]
!CORRECTION! I DID happen to find the .dll but ONLY AFTER finding a seperate download for v2.21-22 on a weird looking site. Hopefully it works but it would be super cool if you included the .dll in the github Master File download. <3

**Comment by KrossX** [comment]
Done, I've uploaded the old file as a release on this repository. Google changed something and invalidated all old links, quite annoying.
