### ISSUE TITLE
EPSXE and PCSX2 Afterplug Issue

### ISSUE THREAD

**Issue by shinra358** [KrossX/Pokopom#7]
When turning on the controller after either emu is started, it presses all buttons on the controller for some reason. Like if you are on a menu screen, Turning the controller on will make the cursor go up one.

I don't know if this is connected or not but in EPSXE when turning off your controller midgame in FF9, it soft resets the whole game. Can you fix this while still keeping the controller disconnect messages in the emus?
This doesn't happen with other plugins.

**Comment by KrossX** [comment]
Maybe ePSXe just freaks out? Pokopom returns invalid data when controller is unplugged so that games themselves can show the message of "Hey! Plug a controller already!".

#EDIT: I'll try changing the invalid value to 0xFF instead of 0x00. As 0x00 might be interpreted as all pressed....

**Comment by shinra358** [comment]
Yeah Im pretty sure it's from a change they made. It's been like this for the past 3 versions and theyve been told about it but still no change. So I was thinking maybe you can go behind and see what's up to modify some of your code to work around their new stuff so that it'll work properly again. Their plugin doesn't do it but their plugin also doesn't bring up controller prompts when a controller is disconnected so it's not accurate.

**Comment by KrossX** [comment]
I have no clue what the proper data should be for a controller not present, so maybe it has been wrong all this time. I'll make a quick change so you can test.

**Comment by shinra358** [comment]
Ok, cool.

**Comment by KrossX** [comment]
Wait a second, using padtest on PCSX2, it only responds to "unplugged" if the value returned is zero as it currently is. So the return value is alright....

**Comment by shinra358** [comment]
pcsx2 only has the problem of buttons getting pressing when you turn the controller on during. I have no clue on what FFIX is doing when you turn the controller off and it resets the whole game. At first I thought this was the other rumble thread. But I dunno what to tell you on this one. All I know is what I can see happening. I already told epsxe about it ages ago so. _shrugs_ lol.

**Comment by shinra358** [comment]
Lilypad's afterplugging doesn't even work so I don't even have anything to compare to.

**Comment by KrossX** [comment]
Try this build: [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7Wl8tMEx4QlJLRzA)

I added a reset on replug, which would actually make sense.

**Comment by shinra358** [comment]
Unfortunately, in pcsx2 (ffxii for example), if I turn the controller on on a menu selection, it auto selects a menu entry instead of just turning on. 

As for FFIX epsxe, the controller still goes up one menu space if you turn the controller on, on the menu and the game still soft resets when you turn the controller off.

**Comment by shinra358** [comment]
I just hooked up my phat ps2 to make sure. I can confirm these behaviors aren't expected behaviors for both games.

Edit: reset issue doesn't happen in pcsx-r

**Comment by KrossX** [comment]
Alright, new build then: [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7NnN4QUg2TUhMMXc)

I think now it should do a full state even if the controller is unplugged in the middle of it.

**Comment by shinra358** [comment]
No dice. Still same outcome. Perhaps if you can go a hack route of disabling the gamepad input for 2 secs when the controller is turned on (at start of initiation) and disable input for 2 secs when controller is turned off (for pcsx2 and epsxe only)?

**Comment by KrossX** [comment]
Maybe if I do that you'll get the soft reset 2 seconds later.

#EDIT: New build: [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7dTY2blRiVEpJSWs)

**Comment by shinra358** [comment]
Sorry I fell asleep. It was like 2am xD
But yeah, see this is why you're my fav dev xD 
It's fixed!
One draw back though, for epsxe, the analog on/off box stays on screen the whole time. Can you make an option that makes it time out disappear and also an option for it never to show at all?

**Comment by KrossX** [comment]
I think it was 5am for the last build in here. =P

I have no clue about the popup, that's someting tied to the internal input plugin and the gpu plugin. Try setting both input ports to the internal plugin and then configure them to be disabled, after that set Pokopom for both ports. I only get a "Standard" popup for a second or so and it would show again if pressing F5/F6.

**Comment by shinra358** [comment]
It only pops up on a hotplug. The new gpu of pete's modified by the epsxe team, it doesn't show at the start BUT if you hotplug during the game, it'll pop up but stay on forever. Until you press F5. For the Tweak version, it pops up for a split second and goes away. However, I don't think it popped up at all during the game (only at start) with the unfixed pokopom.

**Comment by KrossX** [comment]
I have no popup at all except on first boot. I can unplug and plug again and no popup happens. I do however have configured the internal input plugin settings to keyboard/disabled for both ports then swiched back to Pokopom for both ports.

**Comment by shinra358** [comment]
You are correct. What in tarnation. Why is their plugin interferring when it's not even selected for use? P1 had xinput selected so I switched it to keyboard and no more popup when I went back to pokopom. @.@

**Comment by KrossX** [comment]
Probably because the easiest way to support input plugins did not include checking all the ways the internal plugin is integrated into everything.

**Comment by KrossX** [comment]
I'll consider this fixed then.

**Comment by shinra358** [comment]
yeah
