### ISSUE TITLE
Afterplug Rumble Fix Build Scroll Light Randomness

### ISSUE THREAD

**Issue by shinra358** [KrossX/Pokopom#9]
Scroll light starts flickering with both controller port modes being analog mode and only 1 controller activated/on. Afterwards, if I keep pressing the PS button, it'll randomly go to either no light or a solid light. It's not consistent. 

Example:
starts flickering > PS button > random chance of no light
starts flickering > PS button > random chance of solid light

**Comment by KrossX** [comment]
I can fix the random chance, but I dunno about the flickering.

**Comment by KrossX** [comment]
Test build: [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7cUdtMEpubDRHQkU)

**Comment by shinra358** [comment]
No change in random chance.

**Comment by KrossX** [comment]
Alright, new build. [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7U2llQk5GdDdUelk)

If still broken, please tell me the name of the game and attach your pokopom ini.

**Comment by shinra358** [comment]
[padPokopom.zip](https://github.com/KrossX/Pokopom/files/335966/padPokopom.zip)

Flickering and randomness seems fixed in chocobo racing. But it's still there in FFIX. So since those 2 handled the analog light thing differently than each other, try and take a look at it in FFIX. Then I will test other games if you come up with a solution for FFIX to see if everything is covered now or not.

**Comment by KrossX** [comment]
I can't reproduce it with FF9. Can you try ticking the Disabled checkbox on all but Controller 1 ? Restart the emulator after that though.

**Comment by shinra358** [comment]
With chocobo racing, I don't need to disable the 2nd controller for the light to work correctly. But yes, with FF9, disabling the 2nd controller fixes the issue. But un-disabling the 2nd controller, the issue is back with FF9.

Note: I'm only testing with 1 physical controller activated.

**Comment by KrossX** [comment]
Then something is telling Pokopom that controller 2 is still plugged.... hmmm....

Extract this on your ePSXe folder and give it a try: [XTEST](http://www.mediafire.com/download/u5rzhpr58t84ehy/Xinput_test_simple_controller.zip), see if there's something unusual.

**Comment by shinra358** [comment]
I turned controller on and emu and kept pressing the ps button until the light messed up again. Only controller 0 displayed info the whole time. No other controller displayed anything in the program.

**Comment by KrossX** [comment]
I have no idea then! So next build is just a log maker one. [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7MENTMUF4MkE3eUU)

Run the game until you get the light to flicker, then stop. You'll see a pokopom.log file, zip it and post it here please.

**Comment by shinra358** [comment]
Well, on FF9 it's gonna flicker when the game starts. So I'mma send one from that, and also one where the light goes solid twice in a row when pressing the ps button.

**Comment by shinra358** [comment]
Ha, it didn't flicker on start anymore for this buld but I did catch a flickering after about 4 or 5 toggles.
[pokopom log.zip](https://github.com/KrossX/Pokopom/files/337200/pokopom.log.zip)

**Comment by KrossX** [comment]
But, does it stay flickering after that?

#EDIT: I see activity on controller2, so the light indeed goes back and forth between controller1 and 2. Is there any wrapper on use that might be affecting Pokopom? But you did use the tool and showed no other controller activity... _sighs_

**Comment by shinra358** [comment]
When it starts to flicker I left it like that. I couldn't zip it up then because it said the ini was still being used so I had to turn the emu off to zip it up.

At first, it still has that chance of being solid or off twice in a row. But after you get it to flicker. It does the flicker every time you toggle analog on. Whelp, just witnessed it still can flicker when first turning it on too.
If it looks like everything is good, there's a good chance you can trigger it by rapidly pressing the ps button. But I've only had to do that once. Every other time it does it on its own.

**Comment by KrossX** [comment]
New build with just more log data, same operation as before. [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7djQ0aVRtbDJZNzg)

**Comment by shinra358** [comment]
[pokopom.zip](https://github.com/KrossX/Pokopom/files/337946/pokopom.zip)
This one started flickering at start. When I pressed the ps button, it changed to a solid light. When I pressed it again, changed to a flickering light. When I pressed it after that, it changed to a solid light again.

**Comment by KrossX** [comment]
Thank you very much. Did you change your settings from the last test? It seems the same controller is used for both ports. Please recheck the settings so that each port points to a different controller or delete the ini file to restore all defaults.

**Comment by shinra358** [comment]
Somehow I had controller 2 as controller one. Dnt know how that got there : P
Made it correct but it is still the same issue:
[pokopom.zip](https://github.com/KrossX/Pokopom/files/338420/pokopom.zip)

**Comment by KrossX** [comment]
Alright, there are weird things in the log. For once, I don't see any flickering from the controllers setting the light. That means, now it would appear that it should behave as if you had disabled all but controller1.

However, even though controller1 goes from digital to analog and vice versa, every time scrolllock is checked it seems to be off. Now that's troublesome cuz something's turning it off... and it ain't Pokopom.

New build with better log for this. [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7RUt2bFpYdklMUXc)

**Comment by shinra358** [comment]
[pokopom.zip](https://github.com/KrossX/Pokopom/files/338507/pokopom.zip)
Pressed it about 10 times or so. Me pressing scroll lock works fine if I'm pressing it as scrolllock (as normal). Seems weird that it works fine for one game type but not another.

I have a system program that came with the pc that can allow you to always have the caps lock, numlock, and scroll lock on or off by default. That's about it. That doesn't interfere with normal physical presses so I don't see how that could interfere if a program does it. And for one game and not the other to boot.

**Comment by shinra358** [comment]
Hmm, I think it maybe RegEmu32. I removed it and restored the original epsxe exe and the light works fine but when I put regemu32 back on, problem happens again. hmmmmmm.

**Comment by shinra358** [comment]
ah, nope. I don't think it's anythng to do with regemu since pokopom r127 doesn't have this issue @.@
Edit: whelp, I take that back. It's opposite on that old version. chco racing has the prob but ff9 doesnt. On this new one, ff9 has the prob but chco doesnt : P  So back to regemu theory?

**Comment by KrossX** [comment]
Regemu doesn't have anything that would affect Pokopom, as it deals with some ADVAPI32.DLL functions and this plugin doesn't even use that dll to begin with. There's definitely something weird as the log shows that every single time the light was checked the report is the light was OFF

Can you send me a log of when this doesn't happen? Also, do you mind sending your ePSXe directory (minus BIOS and troublesome files that is)?

**Comment by shinra358** [comment]
I've also noticed that without regemu modified exe, I can see the analog box at top right. But with regemu modded exe, I don't see that analog box at top right. Zipping game folder up now.
[pokopom.zip](https://github.com/KrossX/Pokopom/files/340261/pokopom.zip)

**Comment by shinra358** [comment]
https://mega.nz/#!GgNCnIwK!_MAZL1HKNnNPYUbcvQgprw1d9U9QkhoZxQb8T0K2hes

Hopefully it's not something stupid on my part and hopefully regemu is not forgetting any reg entries or something _shrugs_.

**Comment by KrossX** [comment]
Alright, I'll check them out later. As for Regemu, remember that once you stop using it all your settings might be different (Window's registry) and thus all workarounds (like disabling ePSXe controllers) will have to be set again.

**Comment by shinra358** [comment]
Ok. yeah I know. that was done and everythng was set like it was with it on.

**Comment by KrossX** [comment]
I could not reproduce the issue with your folder. I loaded FF9 and plugged the controller while on the start screen, light turned on as expected. Then I pressed the analog button over and over again but I could never get it to flicker. There was no Analog box showing up either.

**Comment by shinra358** [comment]
Found the problem...  http://i0.kym-cdn.com/photos/images/newsfeed/000/103/740/Me%20Gusta.png?1318992465

Don't know why it did it for for some games but not all but.....
It was the infamously buggy ds4-windows j2k's fault. Instead of auto finding the xinput ports, you have to choose them manually. The setting I had it on was the problem. Seem like good ports keep changing every time I plug something new in so I would have no idea really which ports are good at the time which makes this feature problematic. I manually changed the ports to another set and walaa, problem is fixed.

So you can mark this as resolved :)

**Comment by shinra358** [comment]
http://i0.kym-cdn.com/photos/images/newsfeed/000/103/740/Me%20Gusta.png?1318992465

https://youtu.be/BqIXkLNXFUk

*this video is showing the flickering. then showing me switching to the original epsxe exe and then switching back with everything working correctly when it wasn't at first. So below is a suggestion to alleviate this once and for all for both of us lol:

Yeah this is weird. As long as every feature of the controller is actually working let's not even worry about it. But for the sake of not knowing whether or not keyboard leds blow (or as far as we know, it may be a poor keyboard driver), I would like to suggest being able to disable the led through the ini only with its default set to on (and i'll only use like on for debug purposes if I every notice another problem). How's that sound since it seems random for me and no one else but you and me are paying attention? So let's close this topic off with that led ini only option please. That way, my body will always be ready xD

Too bad the last fix wasnt done to NULLDC because that issue was present there too in the 127 build :(

**Comment by KrossX** [comment]
Thanks for the video, now I know I didn't mess up the last test. I can try to make an INI setting for it for now. I thought this was gonna be some silly bug, but ended up some weird random stuff. I'll make some tiny program that does nothing but mess with the scroll lock light so that all the other emulator variables can be removed. 

What nullDC issue? I do have a require with all the supported emus but no customization nor settings dialog yet, maybe it would be easier to fix there.

**Comment by shinra358** [comment]
Ok, cool. 

It doesn't support nulldc anymore but I was talking about the issue that I posted that pcsx2 and epsxe had where when you turn on the controller and it presses everything on the controller in one instance. It of course still resides in the old version that i use for nulldc. That's what I was talking about there.

**Comment by KrossX** [comment]
Alright, finally did the things. New plugin build available with the new ini-only setting. And here's the testing program for messing with the lights: [LIGHTCHECK](http://www.mediafire.com/download/o91q6t7lnqtqyms/lightcheck.zip)

**Comment by shinra358** [comment]
ok cool. pressing esc > continue while the controller is currently rumbling crashes the emu. I don't believe that use to happen. Also, controller continues to rumble when esc is pressed while the controller is rumbling.

**Comment by KrossX** [comment]
Alright. Can you please test with previous versions and make a new issue for it?

**Comment by shinra358** [comment]
done
